apiVersion: v1
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h moodle-project-mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: moodle-project-mariadb-tests
  selfLink: /api/v1/namespaces/default/configmaps/moodle-project-mariadb-tests
