apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: mariadb
    chart: mariadb-6.8.7
    component: master
    heritage: Tiller
    release: moodle-project
  name: moodle-project-mariadb
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/moodle-project-mariadb
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mariadb
      component: master
      release: moodle-project
  serviceName: moodle-project-mariadb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb
        chart: mariadb-6.8.7
        component: master
        release: moodle-project
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: mariadb
                  release: moodle-project
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-root-password
              name: moodle-project-mariadb
        - name: MARIADB_USER
          value: bn_moodle
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-password
              name: moodle-project-mariadb
        - name: MARIADB_DATABASE
          value: bitnami_moodle
        image: docker.io/bitnami/mariadb:10.3.17-debian-9-r37
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: mariadb
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: data
        - mountPath: /opt/bitnami/mariadb/conf/my.cnf
          name: config
          subPath: my.cnf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: moodle-project-mariadb
        name: config
      - emptyDir: {}
        name: data
  updateStrategy:
    type: RollingUpdate
status:
  replicas: 0
