apiVersion: v1
data:
  moodle-password: cGFzc3dvcmQ=
  smtp-password: ""
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: moodle-project-moodle
    chart: moodle-6.1.7
    heritage: Tiller
    release: moodle-project
  name: moodle-project-moodle
  selfLink: /api/v1/namespaces/default/secrets/moodle-project-moodle
type: Opaque
