apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: moodle-project-moodle
    chart: moodle-6.1.7
    heritage: Tiller
    release: moodle-project
  name: moodle-project-moodle
  selfLink: /api/v1/namespaces/default/services/moodle-project-moodle
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: moodle-project-moodle
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
