# Generated by Django 2.2.7 on 2020-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
