# Generated by Django 2.2.7 on 2020-06-13 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_news_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='barTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='botId',
            field=models.IntegerField(default=0),
        ),
    ]
