# Generated by Django 2.2.7 on 2020-06-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20200613_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='source',
            field=models.IntegerField(default=1),
        ),
    ]
