# Generated by Django 2.2.7 on 2020-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_orders_bartime'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='botId',
            field=models.IntegerField(default=0),
        ),
    ]
